[package]
name = "max1726x"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name = "max1726x"
path = "src/lib.rs"

[dependencies]
defmt = "0.3"
embedded-hal = { version = "1", features = ["defmt-03"] }
bitfield = "0.15"
modular-bitfield = "0.11"
